version: '3'

services:
  streamlit_app:
    build: 
      context: ./
      dockerfile: ./content_tools/Dockerfile
    volumes:
      # Just specify a path and let the Engine create a volume
      - ./:/root
    container_name: streamlit_app
    # network_mode: host
    ports:
      - "8501:8501"
    restart: on-failure

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   environment:
  #     - SERVER_NAME=0.0.0.0
  #   restart: always
  #   # network_mode: host
  #   ports:
  #     - "80:80"
  #     - "443:443"