version: "3"

services:
  flaskapp:
    # this is needed to run the app on apple silicon
    platform: linux/amd64
    build: ./
    volumes:
      - ./:/home/mambauser/code
    container_name: flaskapp
    init: true
    tty: true
    ports:
      - "8000:8000"
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    init: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
