version: '3'

services:
  flaskapp:
    build: ./
    volumes:
      # Just specify a path and let the Engine create a volume
      - ./:/root
    container_name: flaskapp
    # network_mode: host
    ports:
      - "8000:8000"
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    # network_mode: host
    ports:
      - "80:80"
      - "443:443"