version: "3"

services:
  flowspeech-ct:
    # this is needed to run the app on apple silicon
    platform: linux/amd64
    build: ./
    volumes:
      - ./:/home/mambauser/code
    image: flowspeech
    container_name: flowspeech-ct
    ports:
      - "8001:8001"
    init: true
    restart: on-failure
    command: ["bash", "content_tools/run_content_tools.sh"]

  nginx-ct:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile_streamlit
    container_name: nginx-ct
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always
    init: true
    ports:
      - "80:80"
      - "443:443"
