FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY web_streamlit.conf /etc/nginx/conf.d/
COPY Q.txt .

RUN chmod 700 /etc/ssl/private

# https://medium.com/geekculture/configure-https-on-aws-ec2-for-free-using-cloudflare-e7120e9a6856
# https://stackoverflow.com/questions/25760596/how-to-terminate-openssl-s-client-after-connection
# https://github.com/lstellway/self-signed-ssl/issues/7
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt < Q.txt