import os
import openai
import re
import random
import ast
import json # everything needs to be accessible in a JSON file import json
import cmudict
cmudict_dict=cmudict.dict() # initializes an access to the CMU dictionary
import exercise_generation.auxiliary as aux
import csv
import pandas as pd

# Generate a response based on a prompt using OpenAI
# https://wandb.ai/ivangoncharov/GPT-3%20in%20Python/reports/Use-GPT-3-in-Python-with-the-OpenAI-API-and-W-B-Tables--VmlldzoxOTg4NTMz

"""
Main/Exercise functions
"""

"""
Generating exercices based on type
General comment: Even though I tackle 7 different exercise types here, some of them can be generated using the same function because they have the same output
                 Count Syllables and Pick stressed syllable have the same output
                 Input Stress Pattern and Pick Stress Pattern have the same output
                 Match Audio to Stress Pattern and Match Word to Stress Pattern have the same output

"""
"""
Topic Parameterization:
Most of the exercises can be adapted in terms of what topic we want the exercises to be based on. If no topic is indicated, the default topic will be Business English (which is the same topic as the examples used as data.)
Topic ideas:
- Financial
- Manufacturing and Operations
- STEM
- Engineering
- Management
- Healthcare
- Medical
- HR
- PR
- Sales and Marketing
- Hospitality & Restaurants
- Catering
- Educational
- Energy and Environment
- Transportation and Logistics
- Maintenance and Mechanics
- Industrial
- Technology
- Mathematics
- Aerounautics
- Automobile
- Science
- Humanities
- Social Sciences
- Literature
- Academic
"""
"""
1) Exercise type : Count Syllables
"""

def count_syllables(n_exercises = 10, topic = "Business"):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI, topic is the topic about which OpenAI will generate vocabulary items
    post: creates a JSON file with a list of dictionaries where the keys are the generated vocabulary items and the values the number of syllables they contain
    Example: [{"photograph": 3}, {"entrepreneur": 4}, {"marketing": 3}, {"business": 2}, {"management": 3}, {"sales": 1}, {"customer": 3}, {"production": 3}, {"financial": 3}, {"legal": 2}, {"transportation": 4}, {"communication": 5}, {"distribution": 4}, {"security": 4}, {"environmental": 5}]
    """
    prompt = "Give me a list of " + str(n_exercises*3) + " words relating to the topic of " + topic + ", in random order. The words need to be at least two syllables long."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)
    l = []
    # if len(liste) >= n_exercises:
    for i in range(min(len(liste), n_exercises)):
        d = {}
        element = random.choice(liste)
        if aux.syllable_count(element) >= 2: # words need to be at least two syllables long to be interesting.
            d['target_content'] = element
            l.append(d)
            liste = list(filter((element).__ne__,(liste)))
    aux.jsonfile(l)
    return l

"""
2) Exercise type : Input Stress Pattern
"""
def input_stress_pattern(n_exercises = 10, topic = "Business"):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI, topic is the topic about which OpenAI will generate vocabulary items
    post: creates a JSON file with a list of dictionaries where the keys are the generated vocabulary items and the values are the stress patterns of these items
    Example: [{"namaste": {"n_syll": 3, "stress_index": 1}}, {"mudra": {"n_syll": 2, "stress_index": 1}}, {"samsara": {"n_syll": 3, "stress_index": 2}}]
    """
    prompt = "Give me a list of "+ str(n_exercises*3)+" words relating to the topic of " + topic + ", in random order. The words need to be at least two syllables long."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)
    l = []
    if len(liste) >= n_exercises:
        for i in range(n_exercises):
            d = {}
            element = random.choice(liste)
            if aux.syllable_count(element) >= 2: # words need to be at least two syllables long to be interesting.
                d['target_content'] = element
                l.append(d)
                liste = list(filter((element).__ne__,(liste)))
    aux.jsonfile(l)
    return l

"""
3) Exercise type : Match Audio to Stress Pattern
Comment: It is important to ask OpenAI to generate long lists of vocabulary, or else the end result will generate almost no exercices because it won't have
enough content to work with. Also, the program currently takes a lot of time to run. Function match_word_to_stress_pattern works much better and reliably in my opinion

"""
def match_audio_to_stress_pattern(n_exercises = 10, topic = "Business"):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI, topic is the topic about which OpenAI will generate vocabulary items
    post: creates a JSON file with a list of dictionaries where the 3 keys are 'target_content','incorrect1' and 'incorrect2'
        and the values are the vocabulary items related to these keys. Number of syllables for each dictionary value must be the same but
        the stress pattern of the 'target_content' key must be different to those of the 'incorrect' keys.
    Example: [{"target_content": "pediatrics", "incorrect1": "cholesterol", "incorrect2": "macrophages"}]
    """
    prompt = "Give me a list of "+ str(n_exercises)+" relating to the topic of " + topic + ", in random order"
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)
    d = aux.syllable_sort(liste)
    final_list = []
    for i in range(20): # tries to generates 20 exercises
        l = []
        key = random.choice(list(d)) # access a random amount of syllables
        for j in range(3):
            item = random.choice(d[key]) # access a random value containing a random amount of syllables
            l.append(item)
        for item in l:
            dico = {}
            if aux.stress_pattern(l[0]) != aux.stress_pattern(l[1]) and aux.stress_pattern(l[0]) != aux.stress_pattern(l[2]) and l[1] != l[2]:
                dico['target_content'] = l[0]
                dico['incorrect1'] = l[1]
                dico['incorrect2'] = l[2]
                final_list.append(dico)
    aux.jsonfile(final_list)

"""
4) Exercise type: Match Word to Audio
Comment: Different types of exercises inside the type itself; Vowel contrast (VC) and words ending in -ed with minimal pairs(ED)
"""
def match_word_to_audio_vc1(n_exercises = 10):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries, where the 2 keys are 'target_content' and 'incorrect1' and the values are
          vocabulary items cotaining the phonemes form VC1.
    Example:[{"target_content": "seat", "incorrect1": "sit"}, {"target_content": "feel", "incorrect1": "fill"}, {"target_content": "keel", "incorrect1": "kill"}, {"target_content": "heel", "incorrect1": "hill"}, {"target_content": "rip", "incorrect1": "reap"}]
    """
    # Creating a Panda Dataframe to retrieve data in CSV file
    df= pd.read_csv("content_tools/content_examples_csvs/match_word_to_audio.csv")
    
    # VC /i:/ and /ɪ/
    match_word_to_audio_vc1 = aux.filter_data(df['VC1'].to_string())    
    prompt = "Here is a list of pairs of words easily confused containing IPA phonemes /i:/ and /ɪ/\n" + match_word_to_audio_vc1 +  "Give me " + str(n_exercises*3)+" more pairs of words like this."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    
    list = text.split('\n')
    del list[0:2] # the first 2 elements are "\n"
    list = aux.remove_numbering(list)
    list = [el.lower() for el in list]
    final_list = []
    for element in list:
        splitted_list = element.split('/')
        if splitted_list[0] in cmudict_dict and splitted_list[1] in cmudict_dict:
            for phon in cmudict_dict[splitted_list[0]][0]:
                if re.search('IH[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('IY[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
                elif re.search('IY[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('IH[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
    l = []
    for element in range(len(final_list)):
        if element%2 == 0: # only evaluates one item out of two, because they all work in pair
            list_slice = final_list[element:element+2]
            x = random.choice(list_slice) # to avoid the vowel contrasts to be always in the same order, we choose randomly whether it is the first or the second element that will be correct
            list_slice.remove(x)
            y = list_slice[0]
            d = {}
            d['target_content'] = x
            d['incorrect1'] = y
            l.append(d)
            if len(l) >= n_exercises:
                break
    aux.jsonfile(l)
    return l

def match_word_to_audio_vc2(n_exercises = 10):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries, where the 2 keys are 'target_content' and 'incorrect1' and the values are
          vocabulary items containing the VC2 phonemes.
    Example:[{"target_content": "maul", "incorrect1": "mole"}, {"target_content": "scroll", "incorrect1": "scrawl"}, {"target_content": "crow", "incorrect1": "crawl"}, {"target_content": "claw", "incorrect1": "crow"}, {"target_content": "straw", "incorrect1": "strow"}]
    """
    # Creating a Panda Dataframe to retrieve data in CSV file
    df= pd.read_csv("content_tools/content_examples_csvs/match_word_to_audio.csv")
    
    # VC /ɔː/ and /əʊ/
    match_word_to_audio_vc2 = aux.filter_data(df['VC2'].to_string())
    prompt = "Here is a list of pairs of words easily confused containing IPA phonemes /ɔː/ and /əʊ/\n" + match_word_to_audio_vc2 + "\nGive me "+ str(n_exercises*3)+" more pairs of words like this"
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    list = text.split('\n')
    del list[0:2] # the first 2 elements are "\n"
    list = aux.remove_numbering(list)
    list = [el.lower() for el in list]
    final_list = []
    for element in list:
        splitted_list = element.split('/')
        if splitted_list[0] in cmudict_dict and splitted_list[1] in cmudict_dict:
            for phon in cmudict_dict[splitted_list[0]][0]:
                if re.search('OW[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('AO[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
                elif re.search('AO[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('OW[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
    l = []
    for element in range(len(final_list)):
        if element%2 == 0: # only evaluates one item out of two, because they all work in pair
            list_slice = final_list[element:element+2]
            x = random.choice(list_slice) # to avoid the vowel contrasts to be always in the same order, we choose randomly whether it is the first or the second element that will be correct
            list_slice.remove(x)
            y = list_slice[0]
            d = {}
            d['target_content'] = x
            d['incorrect1'] = y
            l.append(d)
            if len(l) >= n_exercises:
                break
    aux.jsonfile(l)
    return l
    
def match_word_to_audio_vc3(n_exercises = 10):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries, where the 2 keys are 'target_content' and 'incorrect1' and the values are
          vocabulary items containing the VC3 phonemes.
    Example: [{"target_content": "could", "incorrect1": "cued"}, {"target_content": "would", "incorrect1": "wooed"}, {"target_content": "should", "incorrect1": "shooed"}, {"target_content": "stewed", "incorrect1": "stood"}, {"target_content": "screwed", "incorrect1": "understood"}]
    """
    # Creating a Panda Dataframe to retrieve data in CSV file
    df= pd.read_csv("content_tools/content_examples_csvs/match_word_to_audio.csv")
    
    # VC /ʊ/ vs. /u:/
    match_word_to_audio_vc2 = aux.filter_data(df['VC2'].to_string())
    prompt = "Here is a list of pairs of words easily confused containing IPA phonemes /ɔː/ and /əʊ/\n" + match_word_to_audio_vc2 + "\nGive me " + str(n_exercises*3) + " pairs of words like this, but with the phonemes /ʊ/ (like in 'good') and /u:/ (like in 'use')."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    list = text.split('\n')
    del list[0:2] # the first 2 elements are "\n"
    list = aux.remove_numbering(list)
    list = [el.lower() for el in list]
    final_list = []
    for element in list:
        splitted_list = element.split('/')
        if splitted_list[0] in cmudict_dict and splitted_list[1] in cmudict_dict:
            for phon in cmudict_dict[splitted_list[0]][0]:
                if re.search('UH[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('UW[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
                elif re.search('UH[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('UW[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
    l = []
    for element in range(len(final_list)):
        if element%2 == 0: # only evaluates one item out of two, because they all work in pair
            list_slice = final_list[element:element+2]
            x = random.choice(list_slice) # to avoid the vowel contrasts to be always in the same order, we choose randomly whether it is the first or the second element that will be correct
            list_slice.remove(x)
            y = list_slice[0]
            d = {}
            d['target_content'] = x
            d['incorrect1'] = y
            l.append(d)
            if len(l) >= n_exercises:
                break
    aux.jsonfile(l)
    return l
    
def match_word_to_audio_vc4(n_exercises = 10):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries, where the 2 keys are 'target_content' and 'incorrect1' and the values are
          vocabulary items containing the VC4 phonemes.
    Example: [{"target_content": "hat", "incorrect1": "heart"}, {"target_content": "mat", "incorrect1": "march"}, {"target_content": "chat", "incorrect1": "chart"}, {"target_content": "bar", "incorrect1": "bat"}, {"target_content": "star", "incorrect1": "spat"}]
    """
    # Creating a Panda Dataframe to retrieve data in CSV file
    df= pd.read_csv("content_tools/content_examples_csvs/match_word_to_audio.csv")
    
    # VC /ʊ/ vs. /u:/
    match_word_to_audio_vc2 = aux.filter_data(df['VC2'].to_string())
    prompt = "Here is a list of pairs of words easily confused containing IPA phonemes /ɔː/ and /əʊ/\n" + match_word_to_audio_vc2 + "\nGive me " + str(n_exercises*3) + " pairs of words like this, but with the phonemes /æ/ (like in 'had') and /ɑ:/ (like in 'hard')."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    list = text.split('\n')
    del list[0:2] # the first 2 elements are "\n"
    list = aux.remove_numbering(list)
    list = [el.lower() for el in list]
    final_list = []
    for element in list:
        splitted_list = element.split('/')
        if splitted_list[0] in cmudict_dict and splitted_list[1] in cmudict_dict:
            for phon in cmudict_dict[splitted_list[0]][0]:
                if re.search('AE[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('AA[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
                elif re.search('AA[012]',phon):
                    for phon2 in cmudict_dict[splitted_list[1]][0]:
                        if re.search('AE[012]',phon2):
                            final_list.append(splitted_list[0])
                            final_list.append(splitted_list[1])
    l = []
    for element in range(len(final_list)):
        if element%2 == 0: # only evaluates one item out of two, because they all work in pair
            list_slice = final_list[element:element+2]
            x = random.choice(list_slice) # to avoid the vowel contrasts to be always in the same order, we choose randomly whether it is the first or the second element that will be correct
            list_slice.remove(x)
            y = list_slice[0]
            d = {}
            d['target_content'] = x
            d['incorrect1'] = y
            l.append(d)
            if len(l) >= n_exercises:
                break
    aux.jsonfile(l)
    return l
    
def match_word_to_audio_ed(n_exercises = 10):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries, where the 2 keys are 'target_content' and 'incorrect1' and the values are
          vocabulary items ending in -ed.
    Example:[{"target_content": "crucified", "incorrect1": "created"}, {"target_content": "communicated", "incorrect1": "committed"}, {"target_content": "insisted", "incorrect1": "existed"}, {"target_content": "respected", "incorrect1": "rejected"}, {"target_content": "divided", "incorrect1": "decided"}]
    """
    # Creating a Panda Dataframe to retrieve data in CSV file
    df= pd.read_csv("content_tools/content_examples_csvs/match_word_to_audio.csv")
    
    match_word_to_audio_ed = aux.filter_data(df['-ED'].to_string())
    prompt = "Here is a list of pairs of verbs that sound very similar, ending in -ed\n" + match_word_to_audio_ed + "Give me "+ str(n_exercises*3)+" more pairs of verbs like this"
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    list = text.split('\n')
    del list[0:2] # the first 2 elements are "\n"
    list = aux.remove_numbering(list)
    list = [el.lower() for el in list]
    final_list = []
    for element in list:
        splitted_list = element.split('/')
        if re.search('ed$',splitted_list[0]) and re.search('ed$',splitted_list[1]): # checks if generated keys end with -ed.
            final_list.append(splitted_list[0])
            final_list.append(splitted_list[1])
    l = []
    for element in range(len(final_list)):
        if element%2 == 0: # only evaluates one item out of two, because they all work in pair
            list_slice = final_list[element:element+2]
            x = random.choice(list_slice) # to avoid the vowel contrasts to be always in the same order, we choose randomly whether it is the first or the second element that will be correct
            list_slice.remove(x)
            y = list_slice[0]
            d = {}
            d['target_content'] = x
            d['incorrect1'] = y
            l.append(d)
            if len(l) >= n_exercises:
                break
    aux.jsonfile(l)
    return l


"""
5) Exercise type: Match Word to Stress Pattern
Comment: does not work very well with 5 or 6 syllable words, but in the end very few existing exercises have such long words (only 2 out of 32 exercises)
"""
# 2nd iteration of the function match_audio_to_stress_pattern

def match_word_to_stress_pattern(n_exercises = 10, topic = 'Business'):
    """
    pre: n_syllables is the number of syllables you want your exercise items to have (from 2 to 6, works best from 2 to 4) and topic is the topic you want your generated exercises to be based on
    post: returns a dictionary where the 3 keys are 'target_content','incorrect1' and 'incorrect2'
    and the values are the vocabulary items related to these keys. Number of syllables for each dictionary value must be the same but
    the stress pattern of the 'target_content' key must be different to those of the 'incorrect' keys.
    Example : {"target_content": "appoint", "incorrect1": "budget", "incorrect2": "censure"}
    """
    # To improve OpenAI results, I grouped the existing examples per syllable count in a single CSV file
    df= pd.read_csv("content_tools/content_examples_csvs/match_word_to_stress_pattern.csv")
    # create a dataframe object
    
    l = []
    stress_pattern_dic = {}
    for i in range(2,5):
        examples_filtered = df[str(i)].to_string() # pandas creates a Series object that does not function well in a prompt, so it needs to be adapted
        examples_filtered = re.sub('\d+\s+|NaN\n*','',examples_filtered) # and filtered
        prompt = "Here is a list of " + str(i) + "-syllable words from a Business English vocabulary list.\n" + examples_filtered + "\nGenerate "+ str(n_exercises*3) + " more words that are also " + str(i) + " syllables long and that could be found in a " + topic + " English vocabulary list."
        response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
        text = response.choices[0]['text']
        liste = aux.filter(text)
        l = l + liste # making a big list in hopes of having a lot of words with different stress patterns and number of syllables.
        d = aux.syllable_sort(l)
    for key in list(d.keys()):
        stress_pattern_dic[key] = aux.stress_pattern_sort(d[key]) # we make a dictionary where the keys are different amount of syllables and the values are dictionaries where all the stress patterns with this amount of syllables is represented. The values for these dictionaries in a dictionary are lists of words that follow the stress pattern given in key.
    final_list = []
    for exercise_number in range(n_exercises):
        n_syllables = random.choices([2,3,4], weights=(3, 4, 3), k=1) # we choose a number of syllables at random, but with weighed probabilities
        syllable_dic = stress_pattern_dic[n_syllables[0]]
        if n_syllables[0] in list(stress_pattern_dic.keys()): # we have to make sure not to have a KeyError
            try:
                stress_pattern = random.choice(list(syllable_dic.keys())) # we choose a stress pattern at random that has n_syllables number of syllables in it.
                correct = random.choice(syllable_dic[stress_pattern]) # we choose a word at random that has the stress pattern that was selected at random just before
                exercise = {}
                exercise['target_content'] = correct
                del syllable_dic[stress_pattern]
                if len(syllable_dic) != 0: # There needs to be at least 2 different stress patterns with this amount of syllables
                    stress_pattern = random.choice(list(syllable_dic.keys())) # we choose another stress pattern at random
                    if len(syllable_dic[stress_pattern]) >= 2: # There needs to be at least two entries, because we need an 'incorrect1' and an 'incorrect2'
                        incorrect1 = random.choice(syllable_dic[stress_pattern])
                        exercise['incorrect1'] = incorrect1
                        syllable_dic[stress_pattern] = list(filter((incorrect1).__ne__, (syllable_dic[stress_pattern]))) # remove all instances of this particular word so that it cannot be selected twice
                        incorrect2 = random.choice(syllable_dic[stress_pattern])
                        exercise['incorrect2'] = incorrect2
                        final_list.append(exercise)
            except:
                pass
    aux.jsonfile(final_list)
    
"""
6) Exercise type: Pick Stress Pattern
"""
        
def pick_stress_pattern(n_exercises = 10, topic = 'Business'): # 2nd iteration of the function input_stress_pattern
    """
    pre: n_exercises is the number of exercises you want to generate, topic is the topic you want the exercises to be based on.
    post: creates a JSON file with a list of dictionaries where the keys are the generated vocabulary items and the values are the stress patterns of these items
    Example : [{"businesslike": {"n_syll": 3, "stress_index": 1}}, {"efficient": {"n_syll": 3, "stress_index": 2}}, {"effective": {"n_syll": 3, "stress_index": 2}}, {"responsible": {"n_syll": 4, "stress_index": 2}}, {"productive": {"n_syll": 3, "stress_index": 2}}, {"reliable": {"n_syll": 4, "stress_index": 2}}, {"flexible": {"n_syll": 3, "stress_index": 1}}, {"innovative": {"n_syll": 4, "stress_index": 1}}, {"creative": {"n_syll": 3, "stress_index": 2}}]
    """
    with open('content_tools/content_examples_csvs/pick_stress_pattern.txt') as f:
        pick_stress_pattern = f.read()
    prompt = "Here is a list of words from a Business English vocabulary list.\n" + pick_stress_pattern + "\nGenerate " + str(n_exercises*3) + " words like this that could be in a " + topic + " English vocabulary list and that are at least 2 syllables long."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)
    l = []
    if len(liste) >= n_exercises:
        for i in range(n_exercises):
            element = random.choice(liste)
            d = {}
            if aux.syllable_count(element) >= 2: # words need to be at least two syllables long to be interesting.
                d['target_content'] = element
                l.append(d)
                liste = list(filter((element).__ne__,(liste)))
    aux.jsonfile(l)
    return l
    
"""
7) Exercise type: Pick Stressed Syllable
"""

def pick_stressed_syllable(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the number of exercises you want to generate.
    post: creates a JSON file with a list of dictionaries where the keys are the generated vocabulary items and the values are the stressed syllables of these items
    Example:[{"teamwork": 1}, {"commodity": 2}, {"convey": 2}, {"efficient": 2}, {"intimate": 1}, {"information": 3}, {"enterprise": 1}, {"worldwide": 1}, {"supremacy": 2}, {"clerk": 1}, {"section": 1}, {"cubicle": 1}, {"director": 2}, {"confidentiality": 5}, {"fiscal": 1}, {"tactical": 1}, {"telecommunication": 6}, {"deflation": 2}]
    """
    with open('content_tools/content_examples_csvs/pick_stressed_syllable.txt') as f:
            pick_stressed_syllable = f.read()
    prompt = "Here is a list of words from a Business English vocabulary list, that are at least 2 syllables long.\n" + pick_stressed_syllable + "\nGenerate " + str(n_exercises*3) + " more words like this that are at least 2 syllables long and that could be found in a " + topic + " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)
    l = []
    if len(liste) >= n_exercises:
        for i in range(n_exercises):
            element = random.choice(liste)
            d = {}
            if aux.syllable_count(element) >= 2: # words need to be at least two syllables long to be interesting.
                d['target_content'] = element
                l.append(d)
                liste = list(filter((element).__ne__,(liste)))
    aux.jsonfile(l)
    return l
    
"""
8) Exercise type: Pick Phonetics
"""


def process_response(text, target_regexes, n_exercises):
    """
    pre: text from openAI response (expected to be a numbered list of words), regexes of possible targets that are accepted for filtering, number of exercise that we want
    post: list of dicts formatted as the JSON needed
    """
    liste = aux.filter(text)
    liste=list(set(liste))
    random.Random(0).shuffle(liste)
    l = []
    for element in liste:
        if len(l) < n_exercises:
            phones=cmudict_dict[element][0]
            has_target=sum([sum([re.search(reg,phon)!=None for phon in phones]) for reg in target_regexes])
            if has_target:
                d = {}
                d['target_content'] = element
                l.append(d)
    return l

def pick_phonetics_vc1(n_exercises = 10, topic = 'Business', target_regexes= ['IH[012]', 'IY[012]']):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "testimony"}, {"target_content": "litigation"}, {"target_content": "agreement"}, {"target_content": "jury"}, {"target_content": "negotiations"}]
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_vc1 = aux.filter_data(df['VC1'].to_string())
    prompt = "Here is a list of  of words containing either the IPA phonemes /i:/ or /ɪ/ from a Business English vocabulary list.\n" + pick_phonetics_vc1 + "\nGenerate " + str(n_exercises*3) + " more words that also have either the /i:/ or the /ɪ/ phoneme and that could be found in a " + topic + " English vocabulary list."
    
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    
    l=process_response(text, target_regexes, n_exercises)
    aux.jsonfile(l)
    return l
    
def pick_phonetics_vc2(n_exercises = 10, topic = 'Business', target_regexes= ['OW[012]', 'AO[012]']):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "goal"}, {"target_content": "road"}, {"target_content": "low"}, {"target_content": "tall"}, {"target_content": "blow"},
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_vc2 = aux.filter_data(df['VC2'].to_string())
    prompt = "Here is a list of  of words containing either the IPA phonemes /ɔː/ and /əʊ/ from a Business English vocabulary list.\n" + pick_phonetics_vc2 + "\nGenerate " + str(n_exercises*3) + " more words that also have either the /ɔː/ and /əʊ/ phoneme and that could be found in a " + topic + " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']

    l=process_response(text, target_regexes, n_exercises)
    aux.jsonfile(l)
    return l

def pick_phonetics_vc3(n_exercises = 10, topic = 'Business', target_regexes= ['UH[012]', 'UW[012]']):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "full"}, {"target_content": "pull"}, {"target_content": "wood"}, {"target_content": "took"}, {"target_content": "good"}]
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_vc1 = aux.filter_data(df['VC1'].to_string())
    prompt = "Here is a list of  of words containing either the IPA phonemes /i:/ or /ɪ/ from a Business English vocabulary list.\n" + pick_phonetics_vc1 + "\nGenerate " + str(n_exercises*3) + " words like this, but with the phonemes /ʊ/ (like in 'good') and /u:/ (like in 'pool'), that could be found in a " + topic+ " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l=process_response(text, target_regexes, n_exercises)

    aux.jsonfile(l)
    return l
    
def pick_phonetics_vc4(n_exercises = 10, topic = 'Business', target_regexes= ['AE[012]', 'AA[012]']):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "large"}, {"target_content": "park"}, {"target_content": "smart"}, {"target_content": "dark"}, {"target_content": "start"}]
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_vc1 = aux.filter_data(df['VC1'].to_string())
    prompt = "Here is a list of  of words containing either the IPA phonemes /i:/ or /ɪ/ from a Business English vocabulary list.\n" + pick_phonetics_vc1 + "\nGenerate " + str(n_exercises*3) + " words like this, but with the phonemes /æ/ (like in 'have') and /ɑ:/ (like in 'part'), that could be found in a " + topic+ " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l=process_response(text, target_regexes, n_exercises)

    aux.jsonfile(l)
    return l
    
def pick_phonetics_th(n_exercises = 10, topic = 'Business', target_regexes= ['TH', 'DH']):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "mother"}, {"target_content": "thesis"}, {"target_content": "clothing"}, {"target_content": "method"}, {"target_content": "father"}]
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_vc1 = aux.filter_data(df['VC1'].to_string())
    prompt = "Here is a list of  of words containing either the IPA phonemes /i:/ or /ɪ/ from a Business English vocabulary list.\n" + pick_phonetics_vc1 + "\nGenerate " + str(n_exercises*3) + " words like this, but with the phoneme /θ/ (like in 'method') or /ð/ (like in 'mother'), that could be found in a " + topic+ " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l=process_response(text, target_regexes, n_exercises)

    aux.jsonfile(l)
    return l
    
def pick_phonetics_h(n_exercises = 10, topic = 'Business', target_regexes= ['HH']):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "mother"}, {"target_content": "thesis"}, {"target_content": "clothing"}, {"target_content": "method"}, {"target_content": "father"}]
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_vc1 = aux.filter_data(df['VC1'].to_string())
    prompt = "Here is a list of words containing either the IPA phonemes /i:/ or /ɪ/ from a Business English vocabulary list.\n" + pick_phonetics_vc1 + "\nGenerate " + str(n_exercises*3) + " words like this, but with the phoneme /h/ (like in 'forehead') , that could be found in a " + topic+ " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l=process_response(text, target_regexes, n_exercises)

    aux.jsonfile(l)
    return l



def pick_phonetics_ed(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "approved"}, {"target_content": "restricted"}, {"target_content": "trained"}, {"target_content": "open-ended"}, {"target_content": "hired"}, {"target_content": "completed"}, {"target_content": "employed"}, {"target_content": "requested"}, {"target_content": "denied"}]
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_ed = aux.filter_data(df['-ED'].to_string())
    prompt = "Here is a list of  of words ending in -ed, from a Business English vocabulary list.\n" + pick_phonetics_ed + "\nGenerate " + str(n_exercises*3) + " more words that also end in -ed and that could be found in a " + topic + " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)
    l = []
    for i in range(len(liste)):
        element = random.choice(liste)
        if re.search('ed$',element):
            d = {}
            d['target_content'] = element
            if len(l) < n_exercises:
                l.append(d)
                liste = list(filter((element).__ne__,(liste)))
            else:
                break
    aux.jsonfile(l)
    return l
    
def pick_phonetics_final_s(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content' and the keys are words that fit into the required category
    Example: [{"target_content": "mother"}, {"target_content": "thesis"}, {"target_content": "clothing"}, {"target_content": "method"}, {"target_content": "father"}]
    """
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_ed = aux.filter_data(df['-ED'].to_string())
    prompt = "Here is a list of words ending in -ed from a Business English vocabulary list.\n" + pick_phonetics_ed + "\nGenerate " + str(n_exercises*3) + " words like this, but that end in -s (like 'products' or 'services', that also exist without the final -s, and that could be found in a " + topic+ " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)
    l = []
    for i in range(len(liste)):
        element = random.choice(liste)
        if re.search('s$',element):
            d = {}
            d['target_content'] = element
            if len(l) < n_exercises:
                l.append(d)
                liste = list(filter((element).__ne__,(liste)))
            else:
                break
    aux.jsonfile(l)
    return l
    
"""
9) Exercise type : Pick Audio Unlike Others
"""

def pick_audio_unlike_others_vc1(n_exercises = 10, topic = 'Business'):
    """
    pre: You are asked to fill in the type of exercise you want to create (exercise_type: either equal to 'VC1','VC2' or '-ED')
         and n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file with a list of dictionaries where the keys are 'target_content','incorrect1 and 'incorrect2. For each exercise type,
    (either VC1, VC2 or -ED depending of what has been asked), the 'correct' value has to be different from the two 'incorrect' values, but the two 'incorrect'
    values need to be of the same type
    Example: [{"target_content": "commit", "incorrect1": "belief", "incorrect2": "brief"}, {"target_content": "business", "incorrect1": "achieve", "incorrect2": "brief"}, {"target_content": "competition", "incorrect1": "brief", "incorrect2": "chief"}, {"target_content": "field", "incorrect1": "experience", "incorrect2": "city"}, {"target_content": "field", "incorrect1": "competition", "incorrect2": "business"}]
    """
    # all of the example data is contained in a sorted CSV file
    data = pd.read_csv("content_tools/content_examples_csvs/pick_audio_unlike_others.csv")
    x = data.vc1_long.to_string()
    examples_filtered = re.sub('\d+\s+|NaN\n*','',x) #filtering
    prompt = "Here is a list of words containing the IPA phoneme /i:/ from a Business English vocabulary list.\n" + examples_filtered + "\nGenerate " + str(n_exercises*3) + " more words containing the phoneme /i:/,that could be found in a " + topic + " English vocabulary list."
    response1=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text1 = response1.choices[0]['text']
    liste1 = aux.filter(text1)
    x = data.vc1_short.to_string()
    examples_filtered = re.sub('\d+\s+|NaN\n*','',x) #filtering
    prompt = "Here is a list of words containing the IPA phoneme /ɪ/ from a Business English vocabulary list.\n" + examples_filtered + "\nGenerate " + str(n_exercises*3) + " more words containing the phoneme /ɪ/,that could be found in a " + topic + " English vocabulary list."
    response2=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text2 = response2.choices[0]['text']
    liste2 = aux.filter(text2)
    liste = liste1 + liste2
    # filtering
    phon_dic = {'IH1':[],'IY1':[]}
    for element in liste:
        for phon in cmudict_dict[element][0]:
            if re.search('IH1',phon):
                phon_dic['IH1'].append(element)
            elif re.search('IY1',phon):
                phon_dic['IY1'].append(element)
    l = []
    if len(phon_dic['IH1']) >= 2 and len(phon_dic['IY1']) >= 2 : # we need at least two values for each key, or else we won't be able to generate enough incorrect values.
    # if not enough values are generated for each type, the function will return an empty list
        i = 0
        while len(phon_dic['IH1']) != 1 and len(phon_dic['IY1']) != 1 and i < n_exercises: # specify how many exercises you want to generate so that it never exceeds it
            d = {}
            possibilities = ['IH1','IY1']
            x = random.choice(possibilities)
            possibilities = list(filter((x).__ne__,(possibilities))) # we remove it so that it cannot be selected again for the incorrect values 
            d['target_content'] = random.choice(phon_dic[x])
            y = random.choice(possibilities)
            copy_entry = phon_dic[y] # we make a copy of the dictionary values so that values are not removed from the original
            d['incorrect1'] = random.choice(copy_entry)
            copy_entry = list(filter((d['incorrect1']).__ne__,(copy_entry))) # we remove it so that the same incorrect value cannot be selected twice
            d['incorrect2'] = random.choice(copy_entry)
            l.append(d)
            i += 1
    aux.jsonfile(l)
    return l
    
def pick_audio_unlike_others_vc2(n_exercises = 10, topic = 'Business'):
    data = pd.read_csv("content_tools/content_examples_csvs/pick_audio_unlike_others.csv")
    x = data.vc2_aw.to_string()
    examples_filtered = re.sub('\d+\s+|NaN\n*','',x) #filtering
    prompt = "Here is a list of words containing the IPA phoneme /ɔː/ from a Business English vocabulary list.\n" + examples_filtered + "\nGenerate " + str(n_exercises*3) + " more words containing the phoneme /ɔː/,that could be found in a " + topic + " English vocabulary list."
    response1=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text1 = response1.choices[0]['text']
    liste1 = aux.filter(text1)
    x = data.vc2_ow.to_string()
    examples_filtered = re.sub('\d+\s+|NaN\n*','',x) #filtering
    prompt = "Here is a list of words containing the IPA phoneme /əʊ/ from a Business English vocabulary list.\n" + examples_filtered + "\nGenerate " + str(n_exercises*3) + " more words containing the phoneme /əʊ/,that could be found in a " + topic + " English vocabulary list."
    response2=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text2 = response2.choices[0]['text']
    liste2 = aux.filter(text2)
    liste = liste1 + liste2
    # filtering
    phon_dic = {'AO1':[],'OW1':[]}
    for element in liste:
        for phon in cmudict_dict[element][0]:
            if re.search('AO1',phon):
                phon_dic['AO1'].append(element)
            elif re.search('OW1',phon):
                phon_dic['OW1'].append(element)
    l = []
    if len(phon_dic['AO1']) >= 2 and len(phon_dic['OW1']) >= 2 : # we need at least two values for each key, or else we won't be able to generate enough incorrect values.
    # if not enough values are generated for each type, the function will return an empty list
        i = 0
        while len(phon_dic['AO1']) != 1 and len(phon_dic['OW1']) != 1 and i < n_exercises: # specify how many exercises you want to generate so that it never exceeds it
            d = {}
            possibilities = ['AO1','OW1']
            x = random.choice(possibilities)
            possibilities = list(filter((x).__ne__,(possibilities))) # we remove it so that it cannot be selected again for the incorrect values 
            d['target_content'] = random.choice(phon_dic[x])
            y = random.choice(possibilities)
            copy_entry = phon_dic[y] # we make a copy of the dictionary values so that values are not removed from the original
            d['incorrect1'] = random.choice(copy_entry)
            copy_entry = list(filter((d['incorrect1']).__ne__,(copy_entry))) # we remove it so that the same incorrect value cannot be selected twice
            d['incorrect2'] = random.choice(copy_entry)
            l.append(d)
            i += 1
    aux.jsonfile(l)
    return l
    
def pick_audio_unlike_others_ed(n_exercises = 10, topic = 'Business'):
    data = pd.read_csv("content_tools/content_examples_csvs/pick_audio_unlike_others.csv")
    x = data.ed_td.to_string()
    examples_filtered = re.sub('\d+\s+|NaN\n*','',x) #filtering
    prompt = "Here is a list of verbs ending either in -ted or -ded, from an Business English vocabulary list.\n" + examples_filtered + "\nGenerate " + str(n_exercises*2) + " different verbs that also end in -ted or -ded and that could be found in a " + topic + " English vocabulary list."
    response1=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text1 = response1.choices[0]['text']
    liste1 = aux.filter(text1)
    x = data.ed_voiced.to_string()
    examples_filtered = re.sub('\d+\s+|NaN\n*','',x) #filtering
    prompt = "Here is a list of verbs ending in -ed and preceded either by a voiced consonant or a vowel,  from a Business English vocabulary list.\n" + examples_filtered + "\nGenerate " + str(n_exercises*2) + " different verbs that also end in -ed and are preceded by either a voiced consonant or a vowel, and that could be found in a " + topic + " English vocabulary list."
    response2=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text2 = response2.choices[0]['text']
    liste2 = aux.filter(text2)
    x = data.ed_voiceless.to_string()
    examples_filtered = re.sub('\d+\s+|NaN\n*','',x) #filtering
    prompt = "Here is a list of verbs ending in either /-ched/, /-fed/, /-ked/, /-ped/, /-sed/, /-ced/ or /-shed/, from a Business English vocabulary list.\n" + examples_filtered + "\nGenerate " + str(n_exercises*2) + " different verbs that also end in either /-ched/, /-fed/, /-ked/, /-ped/, /-sed/, /-ced/ or /-shed/and that could be found in a " + topic + " English vocabulary list." 
    response3=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text3 = response3.choices[0]['text']
    liste3 = aux.filter(text3)
    liste = liste1 + liste2 + liste3
    # filtering + sorting by type
    dic_ed = aux.sort_ed(liste)
    l = []
    if len(dic_ed['T']) >= 2 and len(dic_ed['D']) >= 2 and len(dic_ed['AH0D']) >= 2: # we need at least two values for each key, or else we won't be able to generate enough incorrect values.
    # if not enough values are generated for each type, the function will return an empty list
        i = 0
        while len(dic_ed['D']) != 1 and len(dic_ed['T']) != 1 and len(dic_ed['AH0D']) != 1 and i < n_exercises: # specify how many exercises you want to generate so that it never exceeds it
            # if not enough values are generated for each type, the function will return an empty list
            d = {}
            possibilities = ['T','D','AH0D']
            x = random.choice(possibilities)
            possibilities = list(filter((x).__ne__,(possibilities))) # we remove it so that it cannot be selected again for the incorrect values
            d['target_content'] = random.choice(dic_ed[x])
            y = random.choice(possibilities)
            copy_entry = dic_ed[y] # we make a copy of the dictionary values so that values are not removed from the original
            d['incorrect1'] = random.choice(copy_entry)
            copy_entry = list(filter((d['incorrect1']).__ne__,(copy_entry))) # we remove it so that the same incorrect value cannot be selected twice
            d['incorrect2'] = random.choice(copy_entry)
            l.append(d)
            i += 1
    aux.jsonfile(l)
    return l
    
"""
10) Exercise type : SpokenCard
Comment : There are a lot of subcategories here that I have separated to improve the results. They are listed here below
WS-SG: type word stress, format single word (example : development)
WS-WG: type word stress, format word group (example : a *marketing* trend)
WS-S: type word stress, format sentence (example: I am looking for a *permanent* contract.
VC1-SW: type vowel contrast /ɪ/ vs. /i:/, format single word (example : quick)
VC1-WG: type vowel contrast /ɪ/ vs. /i:/, format word group (example : contract *breach*)
VC1-S: type vowel contrast /ɪ/ vs. /i:/, format sentence (example : Mariana is going to start her presentation, you can all take a *seat* please.)
VC2-SW: type vowel contrast /ɔː/ and /əʊ/, format single word (example : low)
VC2-WG: type vowel contrast /ɔː/ and /əʊ/, format word group (example: product *launch*)
VC2-S: type vowel contrast /ɔː/ and /əʊ/, format sentence (example: He travels a lot cause he works *closely* with our foreign partners.)
-ED-WG: type final -ed, format word group (example: highly *skilled*)
-ED-S: type final -ed, format sentence (example: Melania *waited* for a while but she was expected somewhere else.)
"""

#auxilary function/function to only generate one subtype of this exercise

def spokencard_one_type(exercise_type,n_exercises = 10, topic = 'Business'):
    """
    pre: You are asked to fill in the type of exercise you want to create and n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a list of dictionaries where the keys are 'target_content' and the values of these keys are elements
    that fit the required type and format
    Comment: the reason why this function does not immediately create a JSON file is to be able to generate random subtypes using the spokencard() function cf. below
    -> to create a JSON file with the same content as this function, see spokencard_jsonfile(exercise_type,n_exercises = 10, topic = 'Business')
    Example: [{"target_content": "I am looking for a *full-time* position."}, {"target_content": "Who are your main *suppliers*?"}, {"target_content": "Thank you for considering my *application*."}, {"target_content": "He has poor *communication* skills."}, {"target_content": "Good leaders focus on tasks and *people*."}, {"target_content": "*Managers* sell products online."}, {"target_content": "Recruiters use LinkedIn to find *employees*."}, {"target_content": "Let's have dinner to *discuss* our new hire."}, {"target_content": "* Policies* change the way we sell products."}, {"target_content": "I am the chairman of the *board*."}]
    """
    # Creating a panda Dataframe to retrieve all of the example data
    df= pd.read_csv("content_tools/content_examples_csvs/spokencard.csv")
    
    # creating the complements needed for certain types of prompts
    vc1_complement = ", which contains either the phoneme /ɪ/ or /i:/,"
    vc2_complement = ", which contains either the phoneme /ɔː/ or /əʊ/,"
    ed_complement = ", which ends in '-ed',"
    if exercise_type in ['WS-SW','VC1-SW']:
        ws_sw = aux.filter_data(df['WS single word'].to_string())
        vc1_sw = aux.filter_data(df['VC1 single word'].to_string())
        prompt_type = {'WS-SW': [ws_sw,""],'VC1-SW': [vc1_sw,vc1_complement]}
        prompt = "Here is a list of words" + prompt_type[exercise_type][1] + " from a Business English vocabulary list.\n" + prompt_type[exercise_type][0] + "\nGenerate " + str(n_exercises) + " more words that could be found in a " + topic + " English vocabulary list."
        response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
        text = response.choices[0]['text']
        l = text.split('\n')
        del l[0:2] # the first 2 elements are "\n"
        l = aux.remove_numbering(l)
        if exercise_type == 'VC1-SW':
            filtered_list = []
            for element in l:
                if element in cmudict_dict:
                    for phon in cmudict_dict[element][0]:
                        if re.search('IH|IY[012]',phon):
                            filtered_list.append(element)
                            break # if we don't break, the same word could be twice in the list if you have two phonemes that fit the requirements
            l = filtered_list
    elif exercise_type in ['WS-WG','WS-S','VC1-WG','VC1-S','VC2-WG','VC2-S','-ED-WG','-ED-S']:
        ws_wg = aux.filter_data(df['WS word group'].to_string())
        ws_s = aux.filter_data(df['WS sentence'].to_string())
        vc1_wg = aux.filter_data(df['VC1 word group'].to_string())
        vc1_s = aux.filter_data(df['VC1 sentence'].to_string())
        vc2_wg = aux.filter_data(df['VC2 word group'].to_string())
        vc2_s = aux.filter_data(df['VC2 sentence'].to_string())
        ed_wg = aux.filter_data(df['-ED word group'].to_string())
        ed_s = aux.filter_data(df['-ED sentence'].to_string())
        # dictionary to adapt the prompt depending on type of exercise (WS-WG, WS-S, VC1-WG, VC1-S, VC2-WG, VC2-S). 
        prompt_type = {'WS-WG':['word groups',ws_wg,""],'WS-S':['sentences',ws_s,""],'VC1-WG':['word groups',vc1_wg,vc1_complement],'VC1-S':['sentences',vc1_s,vc1_complement],'VC2-WG':['word groups',vc2_wg,vc2_complement],'VC2-S':['sentences',vc2_s,vc2_complement],'-ED-WG':['word groups',ed_wg,ed_complement],'-ED-S':['sentences',ed_s,ed_complement]}
        prompt = "Here is a list of " + prompt_type[exercise_type][0] + " where emphasis on one word in particular" + prompt_type[exercise_type][2] + " is indicated using asterisks (*), from a Business English vocabulary list.\n" + prompt_type[exercise_type][1] + "\nGenerate " + str(n_exercises) + " more " + prompt_type[exercise_type][0] + " where emphasis on one word in particular"  + prompt_type[exercise_type][2] + " is indicated using asterisks (*) and that could be found in a " + topic + " English vocabulary list."
        response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
        text = response.choices[0]['text']
        l = text.split('\n')
        del l[0:2] # the first 2 elements are "\n"
        l = aux.remove_numbering(l)
        if exercise_type in ['VC1-WG','VC1-S','VC2-WG','VC2-S','-ED-WG','-ED-S']: #we have to check wheter the emphasized word indeed contains one of the required phonemes
            filtered_list = []
            for element in l:
                x = re.search('\*.+\*',element) # the word inbetween asterisks has to be isolated
                if x: # only proceeds if asterisks were found
                    y = x.group()
                    y = re.sub("\*", "", y) # asterisks need to be removed to check if entry is in cmudict
                    if exercise_type == '-ED-WG' or exercise_type == '-ED-S': # for these exercise types, the requirements are visible on word level, no need to go to the phonetic level
                        if re.search('ed$',y):
                            filtered_list.append(element)
                    elif y in cmudict_dict:
                        for phon in cmudict_dict[y][0]:
                            if exercise_type == 'VC1-WG' or exercise_type == 'VC1-S':
                                if re.search('IH|IY[012]',phon):
                                    filtered_list.append(element)
                                    break
                            elif exercise_type == 'VC2-WG' or exercise_type == 'VC2-S':
                                if re.search('AO|OW[012]',phon):
                                    filtered_list.append(element)
                                    break
            l = filtered_list                    
    final_list = []
    for word_group in l:
        d = {}
        d['target_content'] = word_group
        final_list.append(d)
    return final_list
    
# same as previous function but result ends up in a JSON file
def spokencard_jsonfile(exercise_type, n_exercises = 10, topic = 'Business'):
    """
    pre: You are asked to fill in the type of exercise you want to create and n_exercises is the number of vocabulary items generated by OpenAI.
    post: creates a JSON file containing a list of dictionaries where the keys are 'target_content' and the values of these keys are elements
    that fit the required type and format
    """
    final_list = spokencard_one_type(exercise_type, n_exercises, topic)
    aux.jsonfile(final_list)
    
        
# final function
def spokencard_vc1(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the number of exercises you want to generate
    post: creates a JSON file containing a list of dictionaries where the keys are 'target_content' and the values are a random (but weighed) selection of the
    different subtypes that can be found in SpokenCard (WS-SW','WS-WG','WS-S','VC1-SW','VC1-WG','VC1-S','VC2-SW','VC2-WG','VC2-S','-ED-WG','-ED-S')
    Example:
    """
    l = []
    choices = ['VC1-SW','VC1-WG','VC1-S']
    for exercise in range(n_exercises):
        ex = spokencard_one_type(random.choices(choices,weights = [3,9,35],k = 1)[0],1,topic)
        if ex != None and len(ex) != 0:
            l.append(ex[0])
    aux.jsonfile(l)
    return l
    
def spokencard_vc2(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the number of exercises you want to generate
    post: creates a JSON file containing a list of dictionaries where the keys are 'target_content' and the values are a random (but weighed) selection of the
    different subtypes that can be found in SpokenCard (WS-SW','WS-WG','WS-S','VC1-SW','VC1-WG','VC1-S','VC2-SW','VC2-WG','VC2-S','-ED-WG','-ED-S')
    Example: [{"target_content": "to be well-*organized*"}, {"target_content": "*orthopedic* surgeon"}, {"target_content": "*open* heart surgery"}]
    """
    l = []
    choices = ['VC2-WG','VC2-S']
    for exercise in range(n_exercises):
        ex = spokencard_one_type(random.choices(choices,weights = [7,25],k = 1)[0],1,topic)
        if ex != None and len(ex) != 0:
            l.append(ex[0])
    aux.jsonfile(l)
    return l
    
def spokencard_ws(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the number of exercises you want to generate
    post: creates a JSON file containing a list of dictionaries where the keys are 'target_content' and the values are a random (but weighed) selection of the
    different subtypes that can be found in SpokenCard (WS-SW','WS-WG','WS-S','VC1-SW','VC1-WG','VC1-S','VC2-SW','VC2-WG','VC2-S','-ED-WG','-ED-S')
    Example: [{"target_content": "The *algorithm* is not working as expected."}, {"target_content": "artificial intelligence"}, {"target_content": "We need to *train* the model with more data."}, {"target_content": "artificial intelligence"}, {"target_content": "artificial intelligence"}, {"target_content": "artificial intelligence"}, {"target_content": "artificial intelligence"}, {"target_content": "algorithm"}, {"target_content": "intelligence"}, {"target_content": "an *AI* system"}]
    """
    l = []
    choices = ['WS-SW','WS-WG','WS-S']
    for exercise in range(n_exercises):
        ex = spokencard_one_type(random.choices(choices,weights = [48,21,18],k = 1)[0],1,topic)
        if ex != None and len(ex) != 0:
            l.append(ex[0])
    aux.jsonfile(l)
    return l
    
def spokencard_ed(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the number of exercises you want to generate
    post: creates a JSON file containing a list of dictionaries where the keys are 'target_content' and the values are a random (but weighed) selection of the
    different subtypes that can be found in SpokenCard (WS-SW','WS-WG','WS-S','VC1-SW','VC1-WG','VC1-S','VC2-SW','VC2-WG','VC2-S','-ED-WG','-ED-S')
    Example: [{"target_content": "The product was *launched* last month."}, {"target_content": "We *launched* the product last week."}, {"target_content": "*tested* products"}, {"target_content": "The new product *launched* last week."}, {"target_content": "We *launched* the product last week."}, {"target_content": "*tested* products"}, {"target_content": "This software *ended* up being very buggy."}, {"target_content": "The product *launched* last week."}]
    """
    l = []
    choices = ['-ED-WG','-ED-S']
    for exercise in range(n_exercises):
        ex = spokencard_one_type(random.choices(choices,weights = [3,19],k = 1)[0],1,topic)
        if ex != None and len(ex) != 0:
            l.append(ex[0])
    aux.jsonfile(l)
    return l

"""
11) Exercise type : Pick Stressed Word
"""

def pick_stressed_word(n_exercises = 10, topic = 'Business'):
    """
    pre: n_exercises is the amount of exercises you want to generate, topic is the topic these exercises are going to be based on.
    post: creates a JSON file containing a list of dictionaries where the keys are 'target_raw' and 'target_content', and the
    values related to these keys are sentences related to the topic at hand. The value of 'target_raw' is a regular sentence and the
    value of 'target_content' is the same sentence but with a emphasized word (indicated by '*').
    Example: [{"target_raw": "We need to optimize our website for search engines.", "target_content": "We need to *optimize* our website for search engines."}, {"target_raw": "I'm not a fan of manual labor.", "target_content": "I'm not a fan of *manual* labor."}, {"target_raw": "We need to automate this process.", "target_content": "We need to *automate* this process."}, {"target_raw": "I always use a calculator when I'm doing math.", "target_content": "I *always* use a *calculator* when I'm doing math."}, {"target_raw": "This algorithm is very efficient.", "target_content": "This *algorithm* is very *efficient*."}, {"target_raw": "This programming language is very popular.", "target_content": "This *programming language* is very *popular*."}, {"target_raw": "This software is very user-friendly.", "target_content": "This *software* is very *user-friendly*."}, {"target_raw": "This database is very reliable.", "target_content": "This *database* is very *reliable*."}, {"target_raw": "This network is very secure.", "target_content": "This *network* is very *secure*."}, {"target_raw": "This computer is very fast.", "target_content": "This *computer* is very *fast*."}]
    """
    with open('content_tools/content_examples_csvs/pick_stressed_word.txt') as f:
        pick_stressed_word = f.read()
    prompt = "Here is a list of sentences where emphasis on one or more words is indicated using asterisks (*), from a Business English vocabulary list.\n" + pick_stressed_word + "\nGenerate " + str(n_exercises) + " more sentences where emphasis on one word in particular is indicated using asterisks (*) and that could be found in a " + topic + " vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l = text.split('\n')
    del l[0:2] # the first 2 elements are "\n"
    l = aux.remove_numbering(l)
    liste = []
    for sentence in l:
        if re.search('\*',sentence) and len(liste) <= n_exercises: # we need to make sure asterisks were actually used.
            d = {}
            d['target_content'] = sentence
            liste.append(d)
    aux.jsonfile(liste)

"""
12) Exercise type : Pick Meaning of Audio
"""
    
def pick_meaning_of_audio(n_exercises = 5, topic = 'Business'):
    """
    pre: n_exercises is the number of exercises you want to generate, topic is the topic you want the generated exercises to be based on.
    post: creates a JSON file with a list of dictionaries where the keys are 'Phrase_audiorecorded', 'target_content', 'incorrect1' and 'incorrect2'. The emphasized (*) part in 'Phrase_audiorecorded' needs to be changed and in all caps in 'target_content'. For 'incorrect1' and 'incorrect2' another part need to be in all caps.
    Example: [{"Phrase_audiorecorded": "*I* invested in Google last year.", "target_content": "YOU didn't invest in Google last year.", "incorrect1": "I INVESTED in Google LAST year.", "incorrect2": "I didn't invest in GOOGLE last year."}, {"Phrase_audiorecorded": "The *value* of my house has gone up.", "target_content": "The VALUE of your house has gone down.", "incorrect1": "The value of MY house has gone UP.", "incorrect2": "The value of the HOUSE has gone up."}, {"Phrase_audiorecorded": "I'm going to *sell* my car.", "target_content": "I'm going to BUY a car.", "incorrect1": "I'm going to SELL my car.", "incorrect2": "I'm going to sell A car."}, {"Phrase_audiorecorded": "I need to *withdraw* some cash from the ATM.", "target_content": "I need to WITHDRAW some cash from the bank.", "incorrect1": "I need to withdraw SOME cash from the ATM.", "incorrect2": "I need to Withdraw some CASH from the ATM."}]
    """
    with open('content_tools/content_examples_csvs/pick_meaning_of_audio.txt') as f:
        pick_meaning_of_audio = f.read()
    prompt = "Here is a list of exercise outputs where emphasis on words is indicated using asterisks (*), from a Business English vocabulary list. Only the word between asterisks should be changed, not another part of the sentence.\n" + pick_meaning_of_audio + "\nGenerate " + str(n_exercises*2) + " exercise outputs that could be found in a " + topic + " English vocabulary list and where at least 4 words are inbetween asterisks."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l = text.split('\n')
    l = aux.remove_numbering(l)
    liste = []
    for output in l:
        if re.search('[{}]',output) and re.search('\*[^\s]+\*.+\*[^\s]+\*.+\*[^\s]+\*.+\*[^\s]+\*',output): # making sure the string looks something like a dictionary and contains 4 words inbetween asterisks.
            try:
                d = ast.literal_eval(output)
                if type(d) == dict: # making sure d was actually transformed into a dictionary
                    liste.append(d)
                l.remove(output)
            except:
                pass
    aux.jsonfile(liste)
    
"""
13) Exercise type : Match Audio to Meaning
"""
    
def match_audio_to_meaning(n_exercises = 5, topic = 'Business'):
    """
    pre: n_exercises is the number of exercises you want to generate, topic is the topic you want the generated exercises to be based on.
    post: post: creates a JSON file with a list of dictionaries where the keys are 'Displayed_text', 'target_content' and 'incorrect1'. The emphasized (*) part in 'Displayed_text' needs to be changed and in all caps in 'target_content'. For 'incorrect1'another part need to be in all caps.
    Example: 
    """
    with open('content_tools/content_examples_csvs/match_audio_to_meaning.txt') as f:
        match_audio_to_meaning = f.read()
    prompt = "Here is a list of exercise outputs where emphasis on words is indicated using asterisks (*), from a Business English vocabulary list. Only the word between asterisks should be changed, not another part of the sentence.\n" + match_audio_to_meaning + "\nGenerate " + str(n_exercises*2) + " more exercise outputs that could be found in a " + topic + " English vocabulary list. There should be one word inbetween asterisks (*) after 'target_content' and one word inbetween asterisks (*) after 'incorrect'."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l = text.split('\n')
    l = aux.remove_numbering(l)
    liste = []
    for output in l:
        if re.search('[{}]',output) and re.search('\*[^\s]+\*.+\*[^\s]+\*',output): # making sure the string looks something like a dictionary and has at least two words inbetween asterisks
            try:
                d = ast.literal_eval(output)
                if type(d) == dict: # making sure d was actually transformed into a dictionary
                    liste.append(d)
            except:
                pass
    if len(liste) > n_exercises: # we have to limit the number of outputs in case there are more than asked for
        liste = liste[:n_exercises]
    aux.jsonfile(liste)
    
"""
14) Exercise type : SpokenSentence
"""
    
def spokensentence_fw(n_exercises = 5, topic = 'Business'):
    """
    pre: You are asked to fill in the type of exercise you want to create and n_exercises is the number of vocabulary items generated by OpenAI 
    post: 
    Example
    """
    # Creating a panda Dataframe to retrieve all of the example data
    df= pd.read_csv("content_tools/content_examples_csvs/spokensentence.csv")
    
    # doesn't work very well, most of the time the output does not have the required format. I think the prompt is a bit too complicated for OpenAI to understand.
    fw_correction_examples = aux.filter_data(df['FW correction'].to_string())
    fw_correction = """Here is a list of exercise outputs from a Business English vocabulary list where emphasis on one word is indicated using asterisks (*)
    in "question", and a correction occurs in "answer", using asterisks (*). The stress category 'Correction' is also indicated in "stress_category".\n""" + fw_correction_examples
    fw_highlight_examples = aux.filter_data(df['FW highlight'].to_string())
    fw_highlight = """Here is a list of exercise outputs from a Business English vocabulary list where emphasis on one word, or none, is indicated using asterisks (*)
    in "question" , and another word is emphasized in "answer", using asterisks (*). The stress category 'Highlight' is also indicated in "stress_category".\n""" + fw_highlight_examples    
    fw_emotion_examples = aux.filter_data(df['FW emotion'].to_string())
    fw_emotion = """Here is a list of exercise outputs from a Business English vocabulary list where emphasis on one word, or none, is indicated using asterisks (*) in "question" ,
    and emotion is expressed in "answer" by emphasizing a word in particular using asterisks (*). The stress category 'Emotion' is also indicated in "stress_category".\n""" + fw_emotion_examples
    prompt1 = fw_correction + "/nGenerate " + str(n_exercises*2) + " more exercise outputs that could be found in a " + topic + " English vocabulary list, alternating between the stress categories 'Correction', 'Highlight' and 'Emotion'."
    response1=aux.generate_response(prompt1, frequency_penalty=0.4,presence_penalty = 0.4)
    text1 = response1.choices[0]['text']
    l1 = text1.split('\n')
    l1 = aux.remove_numbering(l1)
    prompt2 = fw_highlight + "/nGenerate " + str(n_exercises) + " more exercise outputs that could be found in a " + topic + " English vocabulary list."
    response2=aux.generate_response(prompt2, frequency_penalty=0.4,presence_penalty = 0.4)
    text2 = response2.choices[0]['text']
    l2 = text2.split('\n')
    l2 = aux.remove_numbering(l2)
    prompt3 = fw_emotion + "/nGenerate " + str(n_exercises) + " more exercise outputs that could be found in a " + topic + " English vocabulary list."
    response3=aux.generate_response(prompt3, frequency_penalty=0.4,presence_penalty = 0.4)
    text3 = response3.choices[0]['text']
    l3 = text3.split('\n')
    l3 = aux.remove_numbering(l3)
    l = l1 + l2 + l3
    liste = []
    for i in range(len(l)):
        filtered_output = re.search('{.+}',random.choice(l)) # making sure the string looks something like a dictionary
        if filtered_output:
            try:
                d = ast.literal_eval(filtered_output.group())
                if type(d) == dict: # making sure d was actually transformed into a dictionary
                    liste.append(d)
            except:
                pass
    if len(liste) > n_exercises: # we have to limit the number of outputs in case there are more than asked for
        liste = liste[:n_exercises]
    aux.jsonfile(liste)
            
def spokensentence_vc1(n_exercises = 5, topic = 'Business'):
    """
    pre: You are asked to fill in the type of exercise you want to create and n_exercises is the number of vocabulary items generated by OpenAI 
    post: 
    Example
    
    """
    #first step: creating a word list  
    df= pd.read_csv("content_tools/content_examples_csvs/pick_phonetics.csv")
    
    pick_phonetics_vc1 = aux.filter_data(df['VC1'].to_string())
    prompt = "Here is a list of  of words containing either the IPA phonemes /i:/ or /ɪ/ from a Business English vocabulary list.\n" + pick_phonetics_vc1 + "\nGenerate 30 more words that also have either the /i:/ or the /ɪ/ phoneme and that could be found in a " + topic + " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    liste = aux.filter(text)    
    string = ""
    for i in range(len(liste)):
        element = random.choice(liste)
        for phon in cmudict_dict[element][0]:
            if re.search('IH[012]',phon) or re.search('IY[012]',phon): # the word has to contain the required phonemes
                string = string + element + '\n'
                liste = list(filter((element).__ne__,(liste)))
                break
            else:
                break
    # Using the created vocabulary items to make exercise entries
    prompt = "Here is a list of words that contain either the phoneme /i:/ (like in 'leave') or /ɪ/ (like in 'stick'), from a Business English vocabulary list.\n" + string + """Use these words in invented sentences to
    make exercises that have the following format:
    1. {"question": "So, how did the first round of interviews go? ", "answer": "I just *finished*, I think it went pretty well actually. "}
    Only put one word inbetween asterisks in "answer" (*) and that word has to be the word given as example here above. The topic needs to be about """ + topic + "."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l = text.split('\n')
    l = aux.remove_numbering(l)
    filtered_list = []
    for element in l:
        if element not in filtered_list: # we want to avoid entries appearing twice
            x = re.search('answer.+(\*.+\*)',element) # the word inbetween asterisks has to be isolated and has to appear in the second part of the exercise entry
            if x: # only proceeds if asterisks were found
                y = x.group(1)
                y = re.sub("\*", "", y) # asterisks need to be removed to check if entry is in cmudictresponse=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
                if y in cmudict_dict:
                    for phon in cmudict_dict[y][0]:
                        if re.search('IH|IY[012]',phon):
                            filtered_list.append(element)
                            break
        liste = []
        for i in range(len(filtered_list)):
            filtered_output = re.search('{.+}',random.choice(filtered_list)) # making sure the string looks something like a dictionary
            if filtered_output:
                try:
                    d = ast.literal_eval(filtered_output.group())
                    if type(d) == dict: # making sure d was actually transformed into a dictionary
                        if d not in liste:
                            liste.append(d)
                except:
                    pass
    if len(liste) > n_exercises: # we have to limit the number of outputs in case there are more than asked for
        liste = liste[:n_exercises]
    aux.jsonfile(liste)

                        
def spokensentence_vc2(n_exercises = 5, topic = 'Business'):
    """
    pre: You are asked to fill in the type of exercise you want to create and n_exercises is the number of vocabulary items generated by OpenAI 
    post: 
    Example
    """
    # Creating a panda Dataframe to retrieve all of the example data
    df= pd.read_csv("content_tools/content_examples_csvs/spokensentence.csv")
    
    examples = aux.filter_data(df['VC2'].to_string())
    prompt = """Here is a list of exercise outputs from a Business English vocabulary list where emphasis on one word containing either the phoneme /ɔː/ or /əʊ/ is indicated using asterisks (*)
    in "answer".""" + examples + "/nGenerate " + str(n_exercises*2) + " more exercise outputs that could be found in a " + topic + " English vocabulary list."  
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l = text.split('\n')
    l = aux.remove_numbering(l)
    filtered_list = []
    for element in l:
        x = re.search('\*.+\*',element) # the word inbetween asterisks has to be isolated
        if x: # only proceeds if asterisks were found
            y = x.group()
            y = re.sub("\*", "", y) # asterisks need to be removed to check if entry is in cmudictresponse=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
            if y in cmudict_dict:
                for phon in cmudict_dict[y][0]:
                    if re.search('AO|OW[012]',phon):
                        filtered_list.append(element)
                        break
        liste = []
        for i in range(len(filtered_list)):
            filtered_output = re.search('{.+}',random.choice(filtered_list)) # making sure the string looks something like a dictionary
            if filtered_output:
                try:
                    d = ast.literal_eval(filtered_output.group())
                    if type(d) == dict: # making sure d was actually transformed into a dictionary
                        liste.append(d)
                except:
                    pass
    if len(liste) > n_exercises: # we have to limit the number of outputs in case there are more than asked for
        liste = liste[:n_exercises]
    aux.jsonfile(liste)
    
def spokensentence_ed(n_exercises = 5, topic = 'Business'):
    """
    pre: You are asked to fill in the type of exercise you want to create and n_exercises is the number of vocabulary items generated by OpenAI 
    post: 
    Example:
    """
    # Creating a panda Dataframe to retrieve all of the example data
    df= pd.read_csv("content_tools/content_examples_csvs/spokensentence.csv")
    
    examples = aux.filter_data(df['-ED'].to_string())
    prompt = """Here is a list of exercise outputs from a Business English vocabulary list where emphasis on one word, ending in -ed, is indicated using asterisks (*)
    in "answer".""" + examples + "/nGenerate " + str(n_exercises*2) + " more exercise outputs that could be found in a " + topic + " English vocabulary list."
    response=aux.generate_response(prompt, frequency_penalty=0.4,presence_penalty = 0.4)
    text = response.choices[0]['text']
    l = text.split('\n')
    l = aux.remove_numbering(l)
    filtered_list = []
    for element in l:
        x = re.search('\*.+\*',element) # the word inbetween asterisks has to be isolated
        if x: # only proceeds if asterisks were found
            y = x.group()
            y = re.sub("\*", "", y) # asterisks need to be removed to check if entry is in cmudict
            if re.search('ed$',y):
                filtered_list.append(element)
        liste = []
        for i in range(len(filtered_list)):
            filtered_output = re.search('{.+}',random.choice(filtered_list)) # making sure the string looks something like a dictionary
            if filtered_output:
                try:
                    d = ast.literal_eval(filtered_output.group())
                    if type(d) == dict: # making sure d was actually transformed into a dictionary
                        liste.append(d)
                except:
                    pass
    if len(liste) > n_exercises: # we have to limit the number of outputs in case there are more than asked for
        liste = liste[:n_exercises]
    aux.jsonfile(liste)
    
"""
Putting everything together
"""
    
def generate_exercise(exercise_type, pronunciation_aspect = 'VC1', n_exercises = 10, topic = 'Business'):
    """
    pre: exercise_type is a string indicating which exercise type you want to generate, as written in the spreadsheets
    post: returns a JSON file where output is stored for the exercise type that was asked
    """
    if exercise_type == 'Count Syllables': 
        return count_syllables(n_exercises, topic)
    elif exercise_type == 'Input Stress Pattern':
        return input_stress_pattern(n_exercises, topic)
    elif exercise_type == 'Match Audio to Stress Pattern':
        return match_word_to_stress_pattern(n_exercises, topic)
    elif exercise_type == 'Match Word to Audio':
        if pronunciation_aspect == 'VC1':
            return match_word_to_audio_vc1(n_exercises)
        elif pronunciation_aspect == 'VC2':
            return match_word_to_audio_vc2(n_exercises)
        elif pronunciation_aspect == '-ED':
            return match_word_to_audio_ed(n_exercises)
        elif pronunciation_aspect == 'VC3':
            return match_word_to_audio_vc3(n_exercises)
        elif pronunciation_aspect == 'VC4':
            return match_word_to_audio_vc4(n_exercises)
    elif exercise_type == 'Match Word to Stress Pattern':
        return match_word_to_stress_pattern(n_exercises, topic)
    elif exercise_type == 'Pick Stress Pattern':
        return pick_stress_pattern(n_exercises, topic)
    elif exercise_type == 'Pick Stressed Syllable':
        return pick_stressed_syllable(n_exercises, topic)
    elif exercise_type == 'Pick Phonetics':
        if pronunciation_aspect == 'VC1':
            return pick_phonetics_vc1(n_exercises, topic)
        elif pronunciation_aspect == 'VC2':
            return pick_phonetics_vc2(n_exercises, topic)
        elif pronunciation_aspect == '-ED':
            return pick_phonetics_ed(n_exercises, topic)
        elif pronunciation_aspect == 'VC3':
            return pick_phonetics_vc3(n_exercises, topic)
        elif pronunciation_aspect == 'VC4':
            return pick_phonetics_vc4(n_exercises, topic)
        elif pronunciation_aspect == 'TH':
            return pick_phonetics_th(n_exercises, topic)
        elif pronunciation_aspect == 'H':
            return pick_phonetics_h(n_exercises, topic)
        elif pronunciation_aspect == '-S':
            return pick_phonetics_final_s(n_exercises, topic)
    elif exercise_type == 'Pick Audio Unlike Others':
        if pronunciation_aspect == 'VC1':
            return pick_audio_unlike_others_vc1(n_exercises, topic)
        elif pronunciation_aspect == 'VC2':
            return pick_audio_unlike_others_vc2(n_exercises, topic)
        elif pronunciation_aspect == '-ED':
            return pick_audio_unlike_others_ed(n_exercises, topic)
    elif exercise_type == 'SpokenCard':
        if pronunciation_aspect == 'VC1':
            return spokencard_vc1(n_exercises, topic)
        elif pronunciation_aspect == 'VC2':
            return spokencard_vc2(n_exercises, topic)
        elif pronunciation_aspect == '-ED':
            return spokencard_ed(n_exercises, topic)
        elif pronunciation_aspect == 'WS':
            return spokencard_ws(n_exercises, topic)
    elif exercise_type == 'Pick Stressed Word':
        return pick_stressed_word(n_exercises, topic)
    elif exercise_type == 'Pick Meaning of Audio':
        return pick_meaning_of_audio(n_exercises, topic)
    elif exercise_type == 'Match Audio to Meaning':
        return match_audio_to_meaning(n_exercises, topic)
    elif exercise_type == 'SpokenSentence':
        if pronunciation_aspect == 'VC1':
            return spokensentence_vc1(n_exercises, topic)
        elif pronunciation_aspect == 'VC2':
            return spokensentence_vc2(n_exercises, topic)
        elif pronunciation_aspect == '-ED':
            return spokensentence_ed(n_exercises, topic)
        elif pronunciation_aspect == 'FW':
            return spokensentence_fw(n_exercises, topic)