on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # caching docker layers: https://www.hyperdx.io/blog/docker-buildx-cache-with-github-actions
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2

      # - Cache conda downloads
      # See https://pythonspeed.com/articles/docker-cache-pip-downloads/
      # not working?
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       /var/lib/docker/buildkit/cache.db

      - name: Build images
        run: |
          docker buildx create --use --driver=docker-container
          docker buildx bake --set *.cache-to="type=gha,mode=max" --set *.cache-from="type=gha" --load

      - name: docker compose up
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: docker compose up -d

      - name: Check running containers
        run: docker compose ps -a

      - name: Check logs
        run: docker compose logs flowspeech

      # - name: Download hf models
      #   run: docker compose exec flowspeech python scripts/download_models.py

      - name: Set permissions
        run: |
          chmod 777 ./
          chown -R "$(id -u):$(id -g)" ./

      - name: Test with pytest
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: |
          ls -lh
          ls -lh ..
          docker compose exec flowspeech /bin/bash -c "ls -lh"
          docker compose exec flowspeech /bin/bash -c "ls -lh .."
          docker compose exec flowspeech /bin/bash -c "ls -lh hf_models/"
          docker compose exec flowspeech /bin/bash -c "pytest -p no:cacheprovider test_DL_api.py test_DL_modules.py test_models.py"
